version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hiv_postgres
    restart: always
    environment:
      POSTGRES_USER: hiv_user
      POSTGRES_PASSWORD: hiv_pass
      POSTGRES_DB: hiv_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build:
      context: ./user-service
    container_name: user_service
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: src/app.py
      FLASK_RUN_HOST: 0.0.0.0
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: hiv_db
      DB_USER: hiv_user
      DB_PASS: hiv_pass
      JWT_SECRET: your_jwt_secret
    depends_on:
      - postgres

volumes:
  postgres_data:
